# Generated by Django 4.0.5 on 2022-06-17 09:12

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_place_trip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
