# Generated by Django 4.0.5 on 2022-06-17 11:18

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_alter_place_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', tinymce.models.HTMLField(verbose_name='description')),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='place_entry', to='trips.place')),
            ],
        ),
    ]
