# Generated by Django 4.0.5 on 2022-06-21 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0008_trip_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='trips.trip'),
        ),
    ]
