# Generated by Django 4.0.5 on 2022-06-21 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0009_alter_place_trip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='trips/images/'),
        ),
        migrations.AlterField(
            model_name='placeimage',
            name='images',
            field=models.FileField(blank=True, null=True, upload_to='trips/images/'),
        ),
    ]
